#define INVALID -1
#define ADD 0
#define ALSO 1
#define AND 2
#define ASSIGN 3
#define BLANK 4
#define COBEGIN 5
#define CONSTANT 6
#define CONSTRUCT 7
//  #define DIFFERENCE 8
#define DIVIDE 9
#define DO 10
#define ELSE 11
#define ENDCODE 12
#define ENDIF 13
#define ENDLIB 14
#define ENDPROC 15
#define ENDWHEN 16
#define EQUAL 17
#define ERROR 18
#define FIELD 19
//  #define FUNCVAL 20
#define GOTO 21
#define GREATER 22
//  #define IN 23
#define INDEX 24
#define INSTANCE 25
//  #define INTERSECTION 26
#define LESS 27
#define LIBPROC 28
#define MINUS 29
#define MODULO 30
#define MULTIPLY 31
#define NEWLINE 32
#define NOT 33
#define NOTEQUAL 34
#define NOTGREATER 35
#define NOTLESS 36
#define OR 37
#define PARAMARG 38
#define PARAMCALL 39
#define PARAMETER 40
#define PROCARG 41
#define PROCCALL 42
#define PROCEDURE 43
#define PROCESS 44
#define SUBTRACT 45
//  #define UNION 46
#define VALSPACE 47
#define VALUE 48
#define VARIABLE 49
#define WAIT 50
#define WHEN 51
#define WHILE 52
#define ADDR 53
#define HALT 54
#define OBTAIN 55
#define PLACE 56
#define SENSE 57
/** Extra */
#define ELEMASSIGN 58
#define ELEMVALUE 59
#define LOCALCASE 60
#define LOCALSET 61
#define LOCALVALUE 62
#define LOCALVAR 63
#define OUTERCALL 64
#define OUTERCASE 65
#define OUTERPARAM 66
#define OUTERSET 67
#define OUTERVALUE 68
#define OUTERVAR 69
#define SETCONST 70
#define SINGLETON 71
#define STRINGCONST 72

#define PUTI 73
#define PUTC 74
#define PUTB 75
#define PUTN 76

